[project]
name = "vlm-inference"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "argparse-dataclass>=2",
    "bert-score>=0.3",
    "moviepy>=2.2",
    "numpy>=2.4",
    "opencv-python-headless>=4.13",
    "pandas>=2.3",
    "scikit-learn>=1.8",
    "torch>=2.9, <2.10",
    "torchcodec>=0.9",
    "torchvision>=0.24",
    "transformers[accelerate,num2words,sklearn,torch-vision,video]>=4.57",
]

[tool.uv.sources]
torch = { index = "pytorch", marker = "sys_platform != 'darwin'" }
torchvision = { index = "pytorch", marker = "sys_platform != 'darwin'" }
torchcodec = { index = "pytorch", marker = "sys_platform != 'darwin'" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv]
cache-dir = "/AIML/tinyllms/nobackup/.uv_cache"
