[project]
name = "vlm-inference"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "argparse-dataclass>=2",
    "bert-score>=0.3",
    "flash-attn>=2.8.3; sys_platform == 'linux'",
    "gdown>=5.2",
    "moviepy>=2.2",
    "numpy>=2.2",
    "opencv-python-headless>=4.13",
    "pandas>=2.3",
    "scikit-learn>=1.8",
    "torch>=2.9, <2.10", # Flash Attention currently does not have a pre-built wheel for torch 2.10
    "torchcodec>=0.9, <0.10", # 0.10 corresponds to torch 2.10
    "torchvision>=0.24",
    "transformers[accelerate,num2words,sklearn,torch-vision,video]>=4.57",
    "boto3>=1.35",
    "celery[redis]>=5.4",
    "fastapi>=0.115",
    "psycopg[binary]>=3.2",
    "pydantic-settings>=2.6",
    "python-multipart>=0.0.20",
    "sqlalchemy>=2.0",
    "uvicorn[standard]>=0.34",
]

[tool.uv.extra-build-dependencies]
flash-attn = [{ requirement = "torch", match-runtime = true }]

[tool.uv.extra-build-variables]
# The FLASH_ATTENTION_SKIP_CUDA_BUILD environment variable ensures that
# flash-attn is installed from a compatible, pre-built wheel, rather than
# attempting to build it from source, which requires access to the CUDA
# development toolkit. If the CUDA toolkit is not available, the environment
# variable can be omitted, and flash-attn will be installed from a pre-built
# wheel if one is available for the current platform, Python version, and PyTorch version.
flash-attn = { FLASH_ATTENTION_SKIP_CUDA_BUILD = "TRUE" }

[tool.uv.sources]
torch = { index = "pytorch", marker = "sys_platform != 'darwin'" }
torchvision = { index = "pytorch", marker = "sys_platform != 'darwin'" }
torchcodec = { index = "pytorch", marker = "sys_platform != 'darwin'" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "msgpack>=1.0.0",
    "notebook>=7.5.2",
    "pytest>=8.0",
]
